lesson__63/app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from webapp.views import *
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('article/<int:pk>', ArticleView.as_view(), name='article_view'),
    path('articles/add', ArticleCreate.as_view(), name='article_add'),
    path('article/<int:pk>/edit/', ArticleUpdate.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDelete.as_view(), name='article_delete'),
    path('article/<int:pk>/to-favourite/', FavouriteView.as_view(), name='to_favourite'),

    path("accounts/", include('accounts.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson__63/app/webapp/models/articles.py
from django.db import models
from django.contrib.auth.models import User

from webapp.managers import ArticleManager


class Article(models.Model):
    title = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name="Заголовок"
    )
    text = models.TextField(
        max_length=3000,
        null=False,
        blank=False,
        verbose_name='Текст'
    )
    author = models.CharField(
        max_length=40,
        null=False,
        blank=False,
        default='Unknown',
        verbose_name='Автор'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Время изменения'
    )
    tags = models.ManyToManyField(
        to='webapp.Tag',
        related_name='articles',
        blank=True
    )

    users = models.ManyToManyField(
        through='webapp.Favourite',
        to=User,
        related_name='articles'
    )

    objects = ArticleManager()

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

    class Meta:
        permissions = [
            ('сan_have_piece_of_pizza', 'Может съесть кусочек пиццы')
        ]

lesson__63/app/webapp/models/comments.py
from django.db import models


class Comment(models.Model):
    article = models.ForeignKey(
        'webapp.Article',
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Статья'
    )
    text = models.TextField(
        max_length=400,
        verbose_name='Комментарий'
    )
    author = models.CharField(
        max_length=40,
        null=True,
        blank=True,
        default='Аноним',
        verbose_name='Автор'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Время изменения'
    )

    def __str__(self):
        return f'{self.author} : {self.text[:20]}'

lesson__63/app/webapp/models/favourite.py
from django.contrib.auth.models import User
from django.db import models

from webapp.models import Article


class Favourite(models.Model):
    user = models.ForeignKey(to=User, related_name='favourite_articles', verbose_name='Избранное', null=False,
                             on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article, related_name='favourite_users', verbose_name='Избранное', null=False,
                                on_delete=models.CASCADE)
    note = models.CharField(max_length=50, verbose_name='Текстовая заметка', null=False, blank=True)

    class Meta:
        verbose_name = 'Избранная запись'
        verbose_name_plural = 'Избранные записи'

    def __str__(self):
        return f'{self.user} {self.article}'

lesson__63/app/webapp/models/tags.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='Тег'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время создания'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Время изменения'
    )

    def __str__(self):
        return self.name

lesson__63/app/webapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import BaseValidator, MinLengthValidator

from accounts.models import Profile
from .models import *


def max_length_validator(string):
    if len(string) > 10:
        raise ValidationError('Слишком длинно')
    return string


class CustomLengthValidator(BaseValidator):
    def __init__(self, limit_value=20, message=''):
        message = 'Максимальное %(limit_value)s, вы ввели %(show_value)s'
        super(CustomLengthValidator, self).__init__(limit_value=limit_value, message=message)

    def compare(self, value, max_value):
        return max_value < value

    def clean(self, value):
        return len(value)


class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        max_length=200, label='Заголовок',
        validators=(MinLengthValidator(limit_value=2, message='dsad'),
                    CustomLengthValidator())
    )

    class Meta:
        model = Article
        fields = ['title', 'author', 'text']
        widgets = {
            'text': forms.Textarea(attrs={'cols': 73, 'rows': 5, 'class': ''})
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 2:
            raise ValidationError('Длина маленькая')
        if Article.objects.filter(title=title).exists():
            raise ValidationError('уже есть')
        return title


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class FavouriteForm(forms.Form):
    note = forms.CharField(max_length=50, required=True, label='Заметка')


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

lesson__63/app/webapp/views.py
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.utils.http import urlencode
from django.urls import reverse, reverse_lazy

from webapp.forms import ArticleForm, SearchForm, FavouriteForm
from webapp.models import Article

from django.views.generic import View, TemplateView, DetailView, CreateView, UpdateView, DeleteView, ListView, FormView

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from webapp.models.favourite import Favourite


class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'articles'
    model = Article
    ordering = 'created_at'
    paginate_by = 2
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        context['favourite_form'] = FavouriteForm()
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_queryset(self):
        queryset = super().get_queryset().order_by("-title")
        if self.search_value:
            query = Q(title__icontains=self.search_value) | Q(author__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset


class ArticleView(DetailView):
    template_name = 'article_view.html'
    model = Article
    pk_url_kwarg = 'pk'


class ArticleCreate(LoginRequiredMixin, CreateView):
    template_name = 'article_create.html'
    model = Article
    form_class = ArticleForm

    def get_success_url(self):
        return reverse('article_view', kwargs={'pk': self.object.pk})


class ArticleUpdate(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'update.html'
    model = Article
    form_class = ArticleForm
    context_object_name = 'article'

    permission_required = 'webapp.change_article'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name__in=['admin', 'user']).exists:
            raise PermissionDenied
        return super(ArticleUpdate, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('article_view', kwargs={'pk': self.object.pk})


class ArticleDelete(DeleteView):
    template_name = 'delete.html'
    model = Article
    context_object_name = 'article'
    success_url = reverse_lazy('index')


class FavouriteView(LoginRequiredMixin, FormView):
    form_class = FavouriteForm

    def post(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        form = self.get_form_class()(request.POST)
        if form.is_valid():
            note = form.cleaned_data.get('note')
            user = request.user
            # if not Favourite.objects.filter(user=user, article=article).exists():
            Favourite.objects.create(user=user, article=article, note=note)
        return redirect('index')

lesson__63/app/webapp/templates/partial/article_form.html
{% csrf_token %}
<div class="form_error">{{ form.non_field_errors }}</div>
<p>
    <label for="{{ form.title.id_for_label }}">
        {{form.title.label}}
    </label>
    {{form.title}}
<div class="form-error">
    {{form.title.errors}}
</div>
</p>
<p>
    <label for="{{ form.author.id_for_label }}">
        {{form.author.label}}
    </label>
    {{form.author}}
<div class="form-error">
    {{form.author.errors}}
</div>
</p>
<p>
    <label for="{{ form.text.id_for_label }}">
        {{form.text.label}}
    </label>
    {{form.text}}
<div class="form-error">
    {{form.text.errors}}
</div>
</p>
<p><input type="submit" value="{{ button_text }}"></p>

lesson__63/app/webapp/templates/partial/article_list.html
{% if is_paginated %}
{% include 'partial/pagination.html' %}
{% endif %}


{% for article in articles %}
<div class="box">
    <h3><a href="{% url 'article_view' article.pk %}">{{ article.title }}</a></h3>
    <p>
        <label for="selected_articles-{{ article.pk }}">Select:</label>
        <input type="checkbox" name="selected_articles"
               id="selected_articles-{{ article.pk }}" value="{{ article.pk }}">
    </p>
    <p>Статус: ({{ article.status }} | {{ article.get_status_display }})</p>

    <p>Published at: {{ article.publish_at|date:"d.m.Y H:i:s" }}</p>
    {% if perms.webapp.change_article or article.author == request.user %}
    <p><a href="{% url 'article_update' article.pk %}">Update</a></p>
    {% endif %}
    {% if perms.webapp.delete_article or article.author == request.user %}
    <p><a href="{% url 'article_delete' article.pk %}">Delete</a></p>
    {% endif %}
</div>
{% empty %}
<h2 class="text-center">Нет статей</h2>
{% endfor %}


{% if is_paginated %}
{% include 'partial/pagination.html' %}
{% endif %}

lesson__63/app/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1">« В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">В конец »</a>
    </span>
</div>

lesson__63/app/webapp/templates/partial/search.html
<form class="search_form" action="" method="GET">
    <label for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
    {{ form.search }}
    <input type="submit" value="Search">
    {% for error in form.search.errors %}
    <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>